POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Eliot Hernandez 2",
    "number": "0034-666778899"
}

###

# Missing name error
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": "Missing name error"
}

###

# Missing number error
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Missing number error"
}

###

# Name must be unique error
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Arto Vihavainen",
    "number": "040-789012"
}